### ISSUE TITLE
no tabs once again....

### ISSUE THREAD

**Issue by EPiCxRIOTZZ** [insleep/spark-web-browser#24]
u havent added tabs once again, please add tabs in next update

**Comment by insleep** [comment]
Spark is no longer in active development. Tab support will most likely never happen.

**Comment by EPiCxRIOTZZ** [comment]
may i carry it on?

**Comment by insleep** [comment]
Sure thing. You can fork the repository and make your own changes if you like - that's exactly why it's on GitHub
