### ISSUE TITLE
Does not run on 10.9.5 (almost obvious)

### ISSUE THREAD

**Issue by cbertelli** [insleep/spark-web-browser#28]
Hello,
the log is here: 
https://gist.github.com/ef66241b3e2943d52b952d352d804782
Do you think there is a chance to make it work?
Light browsers are great for old PCs that run on old OSs.

**Comment by insleep** [comment]
Unfortunately there are no plans to add support for anything below 10.11 -- I'd imagine the code would all work but the interface would need somewhat major tweaking as it uses some classes that are only in 10.11 and later.
