### ISSUE TITLE
messages.google.com/web/

### ISSUE THREAD

**Issue by gitguys** [insleep/spark-web-browser#32]
Google did some kind of update to their messages app.  I've noticed webkit based browsers including a webkit test browser I generated from Xcode, a Fluid generated webkit app and your webkit browser all do not allow for scrolling through text messages any more.

Strange thing is the scrolling still works with Safari.

Any ideas?

**Comment by insleep** [comment]
I've made a few changes to help solve this in latest nightly channel build (3.4.2n.331). I don't use Google Messages so I'm not sure if it's fixed -- let me know if anything's different.

**Comment by gitguys** [comment]
I switched Spark from stable to nightly and checked for update but nothing happens even after restarting Spark.

**Comment by insleep** [comment]
That is a bug with Sparkle (the auto updater) which has been updated in the latest nightly build, so hopefully it shouldn't happen anymore. You can download the nightly build directly [here](https://spark.insleep.tech/dev/Spark-3.4.2n.331.zip) to skip the auto updater.

**Comment by gitguys** [comment]
Nope, Messages for Web still broken.  Won't allow scrolling of texts, it's just stuck.  I don't know what Google did that WebKit browsers are broken but Safari is fine.

**Comment by insleep** [comment]
Hmm, that's very odd. Unfortunately it seems like something outside the scope of this project so I would recommend submitting feedback to Google, it seems to be an issue on their end.

My apologies! :(
